[project]
name = "unittesting"
version = "0.1.0"
description = "Test gh actions"
authors = [
    {name = "Aleksei Nemtsev",email = "gpuslave@Administrators-Mac-mini.local"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "numpy (>=2.1)",
  "pandas (>=2.2)",
  "scikit-learn (>=1.5)",
  "ucimlrepo (>=0.0.7,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
