name: Unit Tests

env:
  PYTHONPATH: .

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  perf:
    name: Performance Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Setup Global venv
        run: |
          sudo apt update -y || true
          sudo apt install -y --no-install-recommends python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r $GITHUB_WORKSPACE/requirements.txt
      - name: Test R2-performance
        run: |
          PYTHONPATH=. python3 ./test/model_testing.py

          
    
